### ISSUE TITLE
Ynable to get errorformat to work with CMake

### ISSUE THREAD

**Issue by Shatur95** [skywind3000/asynctasks.vim#17]
Hi! I trying to configure `errorformat` for CMake.
[Here](https://github.com/Shatur95/akd) is the example project with few files.
Here is my configuration taken from the wiki:
```ini
[project-build:debug]
command=cd ../build-$(VIM_PRONAME)-debug && cmake --build .
cwd=<root>
errorformat=%f:%m:%l
notify=echo
```
If I remove, for example, `;` after `KeyboardDaemon daemon` in `main.cpp` I have the following error:
```
|| [cd ../build-akd-debug && cmake --build .]
|| [1/2] Building CXX object CMakeFiles/akd.dir/src/main.cpp.o
|| FAILED: CMakeFiles/akd.dir/src/main.cpp.o 
|| /usr/bin/c++    -std=gnu++17 -MD -MT CMakeFiles/akd.dir/src/main.cpp.o -MF CMakeFiles/akd.dir/src/main.cpp.o.d -o CMakeFiles/akd.dir/src/main.cpp.o -c /mnt/Files/Git/akd/src/main.cpp
|| /mnt/Files/Git/akd/src/main.cpp: В функции «int main()»:
|| /mnt/Files/Git/akd/src/main.cpp:31:9: ошибка: expected initializer before «daemon»
||    31 |         daemon.exec();
||       |         ^~~~~~
|| ninja: build stopped: subcommand failed.
|| [Finished in 1 seconds with code 1]
```
But `:cnext`/`:cprev` not works to jump between errors. Is this a bug or am I doing something wrong?

**Comment by skywind3000** [comment]
try %f:%l:%m

**Comment by Shatur95** [comment]
Yes, it worked, thank you!

**Comment by skywind3000** [comment]
FYI:

- a new position, upper case `TAB`, when `-pos=TAB` is provided, a new tab will be created on the left of current tab (instead of on the right of current tab), it is useful because if the command exit and you close the terminal tab you will return to the previous tab like fzf.
- more examples in [wiki](https://github.com/skywind3000/asyncrun.vim/wiki/Customize-Runner) about new runners to run command in another tmux split or a new gnome-terminal window/tab.
